# Generated by Django 5.0.3 on 2024-04-15 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_cliente_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='direccioncliente',
            table=None,
        ),
    ]
