# Generated by Django 5.0.3 on 2024-04-15 04:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha del pedido')),
                ('medio_pago', models.CharField(max_length=100, verbose_name='Medio de pago')),
                ('hora_pedido', models.TimeField(default=django.utils.timezone.now, verbose_name='Hora del pedido')),
                ('horario_entrega', models.TimeField(verbose_name='Horario de entrega')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente', verbose_name='Cliente')),
                ('direccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.direccioncliente', verbose_name='Dirección de entrega')),
            ],
        ),
    ]
